# Usa una imagen oficial de Maven con OpenJDK 17
FROM maven:3.8.7-eclipse-temurin-17 AS build

# Establece el directorio de trabajo
WORKDIR /workspace

# Copia el archivo pom.xml y el código fuente al contenedor
COPY pom.xml ./
COPY src ./src

# Compila la aplicación utilizando Maven
RUN mvn clean package -DskipTests

# Usa la imagen base de OpenJDK para ejecutar la aplicación
FROM registry.access.redhat.com/ubi8/openjdk-17:latest

ENV LANGUAGE='en_US:en'

# Copia los archivos compilados desde la fase de construcción
COPY --chown=185 --from=build /workspace/target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 --from=build /workspace/target/quarkus-app/*.jar /deployments/
COPY --chown=185 --from=build /workspace/target/quarkus-app/app/ /deployments/app/
COPY --chown=185 --from=build /workspace/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
