steps:
  # Construir la imagen del backend
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lq-fresa-internal',
      '-f', 'lq-internal/src/main/docker/Dockerfile.jvm',
      '.'
    ]

  # Push de la imagen del backend al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lq-fresa-internal'
    ]

  # Construir la imagen del frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lq-fresa-frontend',
      '-f', 'lq-frontend/Dockerfile',
      'lq-frontend'
    ]

  # Push de la imagen del frontend al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lq-fresa-frontend'
    ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lq-fresa-internal'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/lq-fresa-frontend'
