steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/lq-fresa-internal',
      '-f', 'lq-internal/src/main/docker/Dockerfile.jvm',
      '.'
    ]

  # Paso 2: Desplegar la imagen en Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'gcloud',
      'run',
      'deploy',
      'lq-fresa-internal',
      '--image', 'gcr.io/$PROJECT_ID/lq-fresa-internal',
      '--platform', 'managed',
      '--region', 'us-west1',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/lq-fresa-internal'

options:
  logging: CLOUD_LOGGING_ONLY
