name: Build and Deploy

on:
  push:
    branches:
      - dev
      - qa
      - main
  delete:
    branches:
      - dev
      - qa
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Google Container Registry
      run: |
        gcloud auth configure-docker

    - name: Build and push lq-internal Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./lq-internal/src/main/docker
        file: ./lq-internal/src/main/docker/Dockerfile.jvm
        push: true
        tags: gcr.io/totemic-sunrise-426016-j3/lq-internal:latest

    - name: Build and push lq-frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: gcr.io/totemic-sunrise-426016-j3/lq-frontend:latest

    - name: Set up `kubectl`
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: totemic-sunrise-426016-j3
        cluster_name: my-cluster
        location: us-central1-a

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f secrets-yaml/
