name: Build and Deploy

on:
  push:
    branches:
      - dev
      - qa
      - main
  delete:
    branches:
      - dev
      - qa
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: my-cluster
  GKE_ZONE: us-central1-a
  DEPLOYMENT_INTERNAL_NAME: lq-internal-deployment
  DEPLOYMENT_FRONTEND_NAME: lq-frontend-deployment
  IMAGE_INTERNAL: lq-internal
  IMAGE_FRONTEND: lq-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Google Container Registry
      run: |
        gcloud auth configure-docker

    - name: Build and push lq-internal Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./lq-internal
        file: ./lq-internal/src/main/docker/Dockerfile.jvm
        push: true
        tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_INTERNAL }}:latest

    - name: Build and push lq-frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./lq-frontend
        file: ./lq-frontend/Dockerfile
        push: true
        tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_FRONTEND }}:latest

    - name: Set up `kubectl`
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Verify gcloud authentication
      run: |
        gcloud auth list
        gcloud config list

    - name: Verify kubectl configuration
      run: |
        kubectl config view
        kubectl config get-contexts
        kubectl config current-context

    - name: Deploy lq-internal to Kubernetes
      run: |
        kubectl set image deployment/${{ env.DEPLOYMENT_INTERNAL_NAME }} ${IMAGE_INTERNAL}=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_INTERNAL }}:latest
        kubectl rollout status deployment/${{ env.DEPLOYMENT_INTERNAL_NAME }}
    
    - name: Deploy lq-frontend to Kubernetes
      run: |
        kubectl set image deployment/${{ env.DEPLOYMENT_FRONTEND_NAME }} ${IMAGE_FRONTEND}=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_FRONTEND }}:latest
        kubectl rollout status deployment/${{ env.DEPLOYMENT_FRONTEND_NAME }}
