name: Build and Deploy

on:
  push:
    branches:
      - dev
      - qa
      - main
  delete:
    branches:
      - dev
      - qa
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Google Container Registry
      run: |
        gcloud auth configure-docker

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    - name: Ensure mvnw is executable
      run: |
        chmod +x ./lq-internal/mvnw

    - name: Build project
      run: |
        cd ./lq-internal
        ./mvnw clean package -DskipTests

    - name: Build and push lq-internal Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./lq-internal
        file: ./lq-internal/src/main/docker/Dockerfile.jvm
        push: true
        tags: gcr.io/totemic-sunrise-426016-j3/lq-internal:latest

    - name: Build and push lq-frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./lq-frontend
        file: ./lq-frontend/Dockerfile
        push: true
        tags: gcr.io/totemic-sunrise-426016-j3/lq-frontend:latest

    - name: Set up `kubectl`
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: totemic-sunrise-426016-j3
        cluster_name: my-cluster
        location: us-central1-a
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Verify gcloud authentication
      run: |
        gcloud auth list
        gcloud config list

    - name: Verify kubectl configuration
      run: |
        kubectl config view
        kubectl config get-contexts
        kubectl config current-context

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f secrets-yaml/ --validate=false
