name: Build and Deploy

on:
  push:
    branches:
      - dev
      - qa
      - master
  delete:
    branches:
      - dev
      - qa
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          gcr.io/totemic-sunrise-426016-j3/lq-internal:latest
          gcr.io/totemic-sunrise-426016-j3/lq-frontend:latest

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure `kubectl`
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: totemic-sunrise-426016-j3
        cluster_name: my-cluster
        location: us-central1-a

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/lq-internal-deployment lq-internal=gcr.io/totemic-sunrise-426016-j3/lq-internal:latest
        kubectl set image deployment/lq-frontend-deployment lq-frontend=gcr.io/totemic-sunrise-426016-j3/lq-frontend:latest
