apiVersion: apps/v1
kind: Deployment
metadata:
  name: lq-internal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lq-internal
  template:
    metadata:
      labels:
        app: lq-internal
    spec:
      containers:
      - name: lq-internal
        image: gcr.io/totemic-sunrise-426016-j3/lq-internal:latest
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_URL_LQFRESA
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: url
        - name: MYSQL_USERNAME_LQFRESA
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD_LQFRESA
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: QUARKUS_HTTP_HOST
          value: "0.0.0.0"
        - name: QUARKUS_HTTP_PORT
          value: "8080"
